import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { Inter } from "next/font/google";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className="antialiased"
      >
         <Navbar />
        {children}
      </body>
    </html>
  );
}
